-- MySQL Script generated by MySQL Workbench
-- Thu Mar 21 10:39:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema alenahanzova
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `alenahanzova` ;

-- -----------------------------------------------------
-- Schema alenahanzova
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alenahanzova` DEFAULT CHARACTER SET utf8 ;
USE `alenahanzova` ;

-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `alenahanzova`.`Adresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alenahanzova`.`Adresa` ;

CREATE TABLE IF NOT EXISTS `alenahanzova`.`Adresa` (
  `idAdresa` INT NOT NULL AUTO_INCREMENT,
  `PSC` VARCHAR(45) NOT NULL,
  `Ulice` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdresa`),
  UNIQUE INDEX `idAdresa_UNIQUE` (`idAdresa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alenahanzova`.`Kontakty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alenahanzova`.`Kontakty` ;

CREATE TABLE IF NOT EXISTS `alenahanzova`.`Kontakty` (
  `idKontakty` INT NOT NULL AUTO_INCREMENT,
  `Predvolba` VARCHAR(4) NULL,
  `Cislo` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKontakty`),
  UNIQUE INDEX `idKontakty_UNIQUE` (`idKontakty` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alenahanzova`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alenahanzova`.`User` ;

CREATE TABLE IF NOT EXISTS `alenahanzova`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Jmeno` VARCHAR(45) NOT NULL,
  `Prijmeni` VARCHAR(45) NOT NULL,
  `Heslo` VARCHAR(90) NOT NULL,
  `Adresa_idAdresa` INT NOT NULL,
  `Kontakty_idKontakty` INT NOT NULL,
  PRIMARY KEY (`idUser`, `Adresa_idAdresa`, `Kontakty_idKontakty`),
  INDEX `fk_User_Adresa1_idx` (`Adresa_idAdresa` ASC) VISIBLE,
  INDEX `fk_User_Kontakty1_idx` (`Kontakty_idKontakty` ASC) VISIBLE,
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_Adresa1`
    FOREIGN KEY (`Adresa_idAdresa`)
    REFERENCES `alenahanzova`.`Adresa` (`idAdresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Kontakty1`
    FOREIGN KEY (`Kontakty_idKontakty`)
    REFERENCES `alenahanzova`.`Kontakty` (`idKontakty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alenahanzova`.`Rezervace`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alenahanzova`.`Rezervace` ;

CREATE TABLE IF NOT EXISTS `alenahanzova`.`Rezervace` (
  `idRezervace` INT NOT NULL,
  `Datum` DATE NULL,
  `Typ` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  `User_Adresa_idAdresa` INT NOT NULL,
  `User_Kontakty_idKontakty` INT NOT NULL,
  PRIMARY KEY (`idRezervace`, `User_idUser`, `User_Adresa_idAdresa`, `User_Kontakty_idKontakty`),
  INDEX `fk_Rezervace_User1_idx` (`User_idUser` ASC, `User_Adresa_idAdresa` ASC, `User_Kontakty_idKontakty` ASC) VISIBLE,
  CONSTRAINT `fk_Rezervace_User1`
    FOREIGN KEY (`User_idUser` , `User_Adresa_idAdresa` , `User_Kontakty_idKontakty`)
    REFERENCES `alenahanzova`.`User` (`idUser` , `Adresa_idAdresa` , `Kontakty_idKontakty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
