-- MySQL Script generated by MySQL Workbench
-- Wed Jun  5 09:48:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema alenahanzova
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `alenahanzova` ;

-- -----------------------------------------------------
-- Schema alenahanzova
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alenahanzova` DEFAULT CHARACTER SET utf8 ;
USE `alenahanzova` ;

-- -----------------------------------------------------
-- Table `alenahanzova`.`Kontakty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alenahanzova`.`Kontakty` ;

CREATE TABLE IF NOT EXISTS `alenahanzova`.`Kontakty` (
  `idKontakty` INT NOT NULL AUTO_INCREMENT,
  `Predvolba` VARCHAR(4) NULL DEFAULT NULL,
  `Cislo` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKontakty`),
  UNIQUE INDEX `idKontakty_UNIQUE` (`idKontakty` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alenahanzova`.`Adresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alenahanzova`.`Adresa` ;

CREATE TABLE IF NOT EXISTS `alenahanzova`.`Adresa` (
  `idAdresa` INT NOT NULL AUTO_INCREMENT,
  `PSC` VARCHAR(45) NOT NULL,
  `Ulice` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdresa`),
  UNIQUE INDEX `idAdresa_UNIQUE` (`idAdresa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alenahanzova`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alenahanzova`.`User` ;

CREATE TABLE IF NOT EXISTS `alenahanzova`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Jmeno` VARCHAR(45) NOT NULL,
  `Prijmeni` VARCHAR(45) NOT NULL,
  `Heslo` VARCHAR(90) NOT NULL,
  `Kontakty_idKontakty` INT NOT NULL,
  `Adresa_idAdresa` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE,
  INDEX `fk_User_Kontakty_idx` (`Kontakty_idKontakty` ASC) VISIBLE,
  INDEX `fk_User_Adresa1_idx` (`Adresa_idAdresa` ASC) VISIBLE,
  CONSTRAINT `fk_User_Kontakty`
    FOREIGN KEY (`Kontakty_idKontakty`)
    REFERENCES `alenahanzova`.`Kontakty` (`idKontakty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Adresa1`
    FOREIGN KEY (`Adresa_idAdresa`)
    REFERENCES `alenahanzova`.`Adresa` (`idAdresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alenahanzova`.`Rezervace`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alenahanzova`.`Rezervace` ;

CREATE TABLE IF NOT EXISTS `alenahanzova`.`Rezervace` (
  `idRezervace` INT NOT NULL AUTO_INCREMENT,
  `Datum` DATE NOT NULL,
  `Mistnost` VARCHAR(45) NOT NULL,
  `cas` TIME NOT NULL,
  `pocetL` INT NOT NULL,
  `Duration` VARCHAR(45) NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idRezervace`, `User_idUser`),
  UNIQUE INDEX `idRezervace_UNIQUE` (`idRezervace` ASC) VISIBLE,
  INDEX `fk_Rezervace_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Rezervace_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `alenahanzova`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alenahanzova`.`Objednavka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alenahanzova`.`Objednavka` ;

CREATE TABLE IF NOT EXISTS `alenahanzova`.`Objednavka` (
  `idObjednavka` INT NOT NULL AUTO_INCREMENT,
  `CisloStolu` INT NOT NULL,
  `jidlo` VARCHAR(45) NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idObjednavka`, `User_idUser`),
  UNIQUE INDEX `idObjednavka_UNIQUE` (`idObjednavka` ASC) VISIBLE,
  INDEX `fk_Objednavka_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Objednavka_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `alenahanzova`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alenahanzova`.`produkt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alenahanzova`.`produkt` ;

CREATE TABLE IF NOT EXISTS `alenahanzova`.`produkt` (
  `idprodukt` INT NOT NULL AUTO_INCREMENT,
  `NazevP` VARCHAR(45) NOT NULL,
  `cena` INT NOT NULL,
  PRIMARY KEY (`idprodukt`),
  UNIQUE INDEX `idprodukt_UNIQUE` (`idprodukt` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alenahanzova`.`produkt_has_Objednavka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alenahanzova`.`produkt_has_Objednavka` ;

CREATE TABLE IF NOT EXISTS `alenahanzova`.`produkt_has_Objednavka` (
  `produkt_idprodukt` INT NOT NULL,
  `Objednavka_idObjednavka` INT NOT NULL,
  PRIMARY KEY (`produkt_idprodukt`, `Objednavka_idObjednavka`),
  INDEX `fk_produkt_has_Objednavka_Objednavka1_idx` (`Objednavka_idObjednavka` ASC) VISIBLE,
  INDEX `fk_produkt_has_Objednavka_produkt1_idx` (`produkt_idprodukt` ASC) VISIBLE,
  CONSTRAINT `fk_produkt_has_Objednavka_produkt1`
    FOREIGN KEY (`produkt_idprodukt`)
    REFERENCES `alenahanzova`.`produkt` (`idprodukt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produkt_has_Objednavka_Objednavka1`
    FOREIGN KEY (`Objednavka_idObjednavka`)
    REFERENCES `alenahanzova`.`Objednavka` (`idObjednavka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
